common:
  loading:
    name: '页面正常'
    xpath: '//div[@id="feeds-replace-loading"]'
  refresh:
    name: '点击刷新'
    xpath: '//div[text()="点击刷新"]'

explore:
  name: '发现'
  xpath: '//li[@id="explore-guide-refresh"]/a'
  topic_list:
    name: '类别'
    xpath: '//div[@class="content-container"]/div'
  section_list:
    name: '类别'
    xpath: '//div[@id="exploreFeeds"]/section'
    _cover:
      name: '封面'
      xpath: '/div/a[2]'
  mention:
    name: '提及'
    xpath: '//div[@class="mention-container-new"]/ul/li[1]'
  detail:
    name: '详情'
    xpath: '//div[@id="noteContainer"]/div[4]'
    _title:
      name: '标题'
      xpath: '//div[@id="detail-title"]'
    _desc:
      name: '描述'
      xpath: '//div[@id="detail-desc"]'
    _datetime:
      name: '发表日期'
      xpath: '//span[@class="date"]'
    _comments_list:
      name: '评论列表'
      xpath: '/div[2]//div[@class="comments-container"]/div[2]/div'
      _me:
        name: '自己'
        xpath: '//div[@class="author"]/span'
      _author:
        name: '用户'
        xpath: '/div[1]//div[@class="author"]/a'
      _content:
        name: '内容'
        xpath: '/div[1]//div[@class="content"]'
      _expand:
        name: '展开'
        xpath: '/div[2]//div[@class="show-more"]'
      _reply:
        name: '回复按钮'
        xpath: '/div[1]//div[@class="reply icon-container"]'
      _inner_list:
        name: '子评论'
        xpath: '/div[2]/div[1]/div'
        _author:
          name: '用户'
          xpath: '//div[@class="author"]/a'
        _content:
          name: '内容'
          xpath: '//div[@class="content"]'
  loading:
    name: '评论加载中'
    xpath: '//div[@class="loading"]'
  like:
    name: '点赞'
    xpath: '//div[@class="interact-container"]//span[@class="like-lottie"]'
  collect:
    name: '收藏'
    xpath: '//div[@class="interact-container"]//span[@id="note-page-collect-board-guide"]'
  comment:
    name: '评论'
    xpath: '//div[@class="interact-container"]//span[@class="chat-wrapper"]'
  input:
    name: '评论输入'
    xpath: '//p[@id="content-textarea"]'
  close:
    name: '关闭'
    xpath: '//div[@class="close-circle"]/div'
  me:
    name: '我'
    xpath: '//ul[@class="channel-list"]//li[4]/div/a'
    note:
      name: '笔记'
      xpath: '//span[text()="笔记"]'
    user_name:
      name: '用户名'
      xpath: '//div[@class="user-name"]'
    note_list:
      name: '笔记列表'
      xpath: '//div[@id="userPostedFeeds"]/section'
      _onlyme:
        name: '仅自己可见'
        xpath: '//div[@class="bottom-wrapper"]'
      _cover:
        name: '封面'
        xpath: '/div/a[2]'

search:
  name: '搜索结果'
  xpath: '//div[@id="user"]'
  user:
    name: '用户'
    xpath: '//div[@class="feeds-page"]/div[3]/div[1]/div/a'
  user_name:
    name: '用户名'
    xpath: '//div[@class="user-nickname"]/div[@class="user-name"]'
  section_one:
    name: '笔记1'
    xpath: '//div[@id="userPostedFeeds"]/section[1]'
  section_list:
    name: '笔记列表'
    xpath: '//div[@id="userPostedFeeds"]/section'
    _url:
      name: '地址'
      xpath: '/div/a[2]'
    _cover:
      name: '封面'
      xpath: '/div/a[2]/img'
    _title:
      name: '标题'
      xpath: '//a[@class="title"]/span'
    _count:
      name: '点赞量'
      xpath: '//span[@class="count"]'