# 个人信息
media:
  xhs:
    - platform: 'xiaohongshu'             # 固定
      account: 'RuMengAI'                 # 数据保存文件夹名, 任意取
      headless: False                     # 无头模式启动浏览器, False会打开浏览器界面
#      proxy: 'close'                     # 使用代理后会被默认保存, 填写close关闭代理
      proxy: ''  # 代理地址
      location: [121.522331,31.236907]    # 浏览器经纬度, 这个是上海

      creator:                          # 配置: 小红书创作者中心
        upload: True                    # 是否自动上传视频/图文
        download: ['美食', '知识']        # 下载灵感笔记数据
      base:         # 配置: 小红书官网页
        me:         # 个人消息页配置
          days: 7   # 只回复最近7天发表的图文
          default: 'AI社交达人🤝'    # 固定评论
          prompt: '你是一位社交达人，某人评论了你的作品，你需要回复他。不要输出回复内容以外的文字。'   # 配置了302__APIKEY则使用AI的提示词
        explore:                            # 配置: 小红书发现页
          topics: ['美食', '影视', '旅行']    # 浏览的主题
          times: 3                         # 每个主题浏览几篇内容
          actions: ['点赞', '收藏', '评论' ]  # 浏览内容执行的动作
          mention: ['RuMengAI', ]           # 评论时@某人, 小红书用户名
          default: 'AI社交达人🤝'             # 固定评论
          prompt: '你是一位社交达人，正在浏览小红书，你也想评论一句。不要输出回复内容以外的文字。'   # 配置了302__APIKEY则使用AI的提示词
        download:
          ids: ['5523405376', ]               # 下载某人小红书账号数据
          data_dir: 'notes'                # 保存目录, data/...
        comment:                            # 配置: 浏览指定用户内容
          ids: ['5523405376', ]               # 指定用户的小红书号
          times: 3                          # 查看每个用户的3条内容
          actions: ['点赞', '收藏', '评论']   # 执行的动作
          mention: ['5523405376', ]           # 如果需要评论, 评论时提及某人, 小红书用户名
          shuffle: False                    # 是否随机选择用户的内容, False则会顺序浏览
          default: 'AI社交达人🤝'             # 固定评论
          prompt: '你是一位社交达人，正在浏览小红书，你也想评论一句。不要输出回复内容以外的文字。'   # 配置了302__APIKEY则使用AI的提示词

  dy:
    - platform: 'douyin'        # 固定
      account: 'RuMengAI'       # 数据保存文件夹名, 任意取
      headless: False           # 无头模式启动浏览器, False会打开浏览器界面
#      proxy: 'close'           # 使用代理后会被默认保存, 填写close关闭代理
      proxy: ''   # 代理地址
      location: [121.522331, 31.236907]   # 浏览器经纬度, 这个是上海

      creator:                      # 配置: 抖音创作者中心
        upload: True                # 是否自动上传视频/图文
        downloader:                 # 配置: 下载创作者中心的数据
          manage: True              # 下载作品管理页数据
          datacenter: False         # 下载数据中心页数据, 有的账户没有
          creative_guidance: ['美食', '科技', '财经']    # 下载创作灵感页数据
          billboard: ['音乐', '美食', '科技', '财经']     # 下载抖音排行榜数据
        operator_comment:           # 配置: 自动处理评论
          days: 7                   # 处理最近7天的评论
          default: 'AI社交达人🤝'    # 固定评论
          prompt: '你是一位社交达人，某人评论了你的作品，你需要回复他。不要输出回复内容以外的文字。'   # 配置了302__APIKEY则使用AI的提示词
        operator_chat:              # 配置: 自动处理私聊
          default: 'AI社交达人🤝'    # 固定评论
          prompt: '你是一位社交达人，某人评论了你的作品，你需要回复他。不要输出回复内容以外的任何信息'   # 配置了302__APIKEY则使用AI的提示词
      base:                                             # 配置: 抖音官网首页
        discover:                                       # 浏览抖音首页视频
          topics: ['首页', '娱乐榜']                      # 浏览的榜单, 输入"首页"则首页随机刷
          times: 3                                     # 每个榜单点击几个视频
          actions: ['点赞', '收藏', '评论']               # 浏览时执行的动作
          mention: ['52320237368', ]                    # 如果需要评论, 评论时提及某人, 抖音号
          default: 'AI社交达人🤝'                         # 固定评论
          prompt: '你是一位社交达人，正在浏览抖音，你也想评论一句。不要输出回复内容以外的文字。'   # 配置了302__APIKEY则使用AI的提示词
        download:                           # 配置: 将指定户视频数据下载到本地
          ids: ['52320237368', ]            # 指定用户的抖音号
          data_dir: 'videos'                # 保存目录, data/...
        comment:                            # 配置: 浏览指定用户视频
          ids: ['52320237368', ]            # 指定用户的抖音号
          times: 3                          # 每个用户浏览3个视频
          actions: ['点赞', '收藏', '评论']   # 浏览时执行的动作
          mention: ['52320237368', ]        # 如果需要评论, 评论时提及某人, 抖音号
          shuffle: False                    # 随机选择浏览用户的视频, False则顺序浏览
          default: 'AI社交达人🤝'             # 固定评论
          prompt: '你是一位社交达人，正在浏览抖音，你也想评论一句。不要输出回复内容以外的文字。'     # 配置了302__APIKEY则使用AI的提示词
        follow:                                                 # 配置: 在指定用户视频评论区私聊
          ids: ['52320237368', ]                                # 用户的抖音号
          times: 3                                              # 每个用户选择3个视频
          batch: 3                                              # 每个视频评论区选择3个好友
          shuffle: False                                        # 随机选择用户的视频, False则顺序浏览
          default: '你好，我是RuMengAI开发的社交AI，很高兴认识你。'    # 给陌生人打招呼时固定话术
          prompt: '根据评论信息，你认为这位用户可以添加好友聊聊天嘛？回复“yes”表示可以，“no”表示不可以或者不清楚。不要回复“yes/no”之外的其他内容。' # 配置了302__APIKEY则使用AI的提示词, 利用AI寻找目标用户, 必须回答yes才会私聊
