media:
  xhs:
    - platform: 'xiaohongshu'             # 固定
      account: 'RuMengAI'                 # 数据保存文件夹名, 任意取
      headless: False                     # 无头模式启动浏览器, False会打开浏览器界面
      proxy: 'close'                      # 使用代理后会被默认保存, 填写close关闭代理

      common:
        # 小红书网页版无法私聊
        default_comment_message: '谢谢分享！'            # 评论别人作品默认消息
        default_comment_reply_message: '谢谢评论！'      # 回复别人对自己的作品评论的默认消息

        default_data_length: 5                        # 默认获取数据长度: 10条
        default_reply_comment_length: 5               # 默认回复评论数量: 10条
        default_reply_comment_days: 3                  # 默认回复最近7天的图文
        default_reply_comment_times: 3                 # 默认回复最近5篇图文

        default_video_wait: 15                         # 默认上传视频最长等待时间min
        default_image_wait: 3                          # 默认上传图片最长等待时间min

        # 在.env中配置 302__APIKEY 之后可以启用AI功能
        # 浏览内容时判断是否过滤, 回复True保留, False过滤
        ai_prompt_content_filter: '根据给出的内容判断该内容描述与"美食"相关嘛? 请回答 True/False. True表示相关性很大, False表示相关性不高或没有相关性.'
        # 根据作品标题,内容+前5条有效评论作为参考. 发表评论
        ai_prompt_content_comment: '我们正在对你进行"图灵测试", 你扮演的身份是小红书平台一位"美食"博主, 你需要给一段"笔记"做评论. 我们将根据你的评论内容做判断: 如果被认为是"美食"博主, 你将得到全部奖励(+100分); 如果被识别出是AI, 你将受到惩罚(-100分); 此外, 如果回复内容不超过30字, 额外奖励(+30分). 请尽量争取最高得分. 回答时不要包含任何解释性表述.'
        # 根据作品标题,内容+用户评论作为参考. 回复对方
        ai_prompt_content_comment_reply: '我们正在对你进行"图灵测试", 你扮演的身份是小红书平台一位"美食"博主, 有人对你发布的"笔记"做了评论, 你需要给"游客"做回复. 我们将根据你的回复内容做判断: 如果被认为是"美食"博主, 你将得到全部奖励(+100分); 如果被识别出是AI, 你将受到惩罚(-100分); 此外, 如果回复内容不超过30字, 额外奖励(+30分). 请尽量争取最高得分. 回答时不要包含任何解释性表述.'

      creator:                               # 配置: 小红书创作者中心
        upload: False                         # 是否自动上传视频/图文
        download: ['美食', '知识']             # 下载灵感笔记数据
      home:                                   # 配置: 小红书官网页
        operate:
          comment: True                      # 配置: 自动回复评论, 回复内容由"default_comment_reply_message"或"ai_prompt_content_comment_reply"决定
        explore:                             # 配置: 浏览小红书发现页, 通过"ai_prompt_content_filter"可以过滤视频内容
          topics: ['美食', '影视']     # 浏览的主题
          times: 1                           # 每个主题浏览几篇内容
          actions: ['点赞', '收藏', '评论']   # 浏览内容执行的动作, 评论内容由"default_comment_message"或"ai_prompt_content_comment"决定
          mention: ['RuMengAI', ]            # 评论时@某人, 小红书用户名
        download:
          ids: ['5523405376', ]              # 下载某人小红书账号数据用户名和小红书号都可, 小红书号更精确
        comment:                             # 配置: 浏览指定用户内容
          ids: ['RuMengAI', ]                # 指定用户的小红书号
          times: 1                           # 查看每个用户的3条内容
          actions: ['点赞', '收藏', '评论']    # 执行的动作, 评论内容由"default_comment_message"或"ai_prompt_content_comment"决定
          mention: ['RuMengAI', ]            # 如果需要评论, 评论时提及某人, 小红书用户名
          shuffle: False                     # 是否随机选择用户的内容, False则会顺序浏览

  dy:
    - platform: 'douyin'        # 固定
      account: 'RuMengAI'       # 数据保存文件夹名, 任意取
      headless: False           # 无头模式启动浏览器, False会打开浏览器界面
      proxy: 'close'            # 使用代理后会被默认保存, 填写close关闭代理

      common:
        default_comment_message: '谢谢分享！'            # 评论别人作品默认消息
        default_comment_reply_message: '谢谢评论！'      # 回复别人对自己的作品评论的默认消息
        default_chat_message: '你好, 🤝'                # 主动私聊别人默认消息
        default_chat_reply_message: '你好👐'            # 回复别人私聊默认消息

        default_data_length: 5                        # 默认获取有效数据长度: 10条
        default_reply_chat_length: 5                  # 默认回复私聊数量: 10条
        default_reply_comment_length: 5               # 默认回复评论数量: 10条
        default_reply_comment_days: 7                  # 默认回复最近7天的图文
        default_reply_comment_times: 3                 # 默认回复最近5篇图文

        default_video_wait: 15                         # 默认上传视频最长等待时间min
        default_image_wait: 3                          # 默认上传图片最长等待时间min

        # 在.env中配置 302__APIKEY 之后可以启用AI功能
        # 浏览内容时判断是否过滤, 回复True保留, False过滤
        ai_prompt_content_filter: '根据给出的内容判断该内容描述与"游戏"相关嘛? 请回答 True/False. True表示相关性很大, False表示相关性不高或没有相关性.'
        # 通过评论判断是否为目标用户, 回复True保留, False过滤. True则主动发送私聊消息 default_chat_message
        ai_prompt_user_filter: '根据给出的内容判断该评论用户对"游戏"感兴趣嘛? 请回答 True/False. True表示感兴趣, False表示无法判断或不感兴趣.'
        # 根据作品标题,内容+前5条有效评论作为参考. 发表评论
        ai_prompt_content_comment: '我们正在对你进行"图灵测试", 你扮演的身份是抖音平台一位"游戏"主播, 你需要给一段"视频"做评论. 我们将根据你的评论内容做判断: 如果被认为是"游戏"主播, 你将得到全部奖励(+100分); 如果被识别出是AI, 你将受到惩罚(-100分); 此外, 如果回复内容不超过30字, 额外奖励(+30分). 请尽量争取最高得分. 回答时不要包含任何解释性表述.'
        # 根据作品标题,内容+用户评论作为参考. 回复对方
        ai_prompt_content_comment_reply: '我们正在对你进行"图灵测试", 你扮演的身份是抖音平台一位"游戏"主播, 有人对你发布的视频做了评论, 你需要给"游客"做回复. 我们将根据你的回复内容做判断: 如果被认为是"游戏"主播, 你将得到全部奖励(+100分); 如果被识别出是AI, 你将受到惩罚(-100分); 此外, 如果回复内容不超过30字, 额外奖励(+30分). 请尽量争取最高得分. 回答时不要包含任何解释性表述.'
        # 如果有人发消息, 根据最后5条对话内容作为参考, 回复对方
        ai_prompt_content_chat_reply: '我们正在对你进行"图灵测试", 你扮演的身份是抖音平台一位"游戏"主播, "对方"正在与你聊天, 我们将根据你的回复内容做判断: 如果被认为是"游戏"主播, 你将得到全部奖励(+100分); 如果被识别出是AI, 你将受到惩罚(-100分); 此外, 如果回复内容不超过30字, 额外奖励(+30分). 请尽量争取最高得分. 回答时不要包含任何解释性表述.'

      creator:                      # 配置: 抖音创作者中心
        upload: False                # 是否自动上传视频/图文
        download:                 # 配置: 下载创作者中心的数据
          manage: True              # 下载作品管理页数据
          datacenter: False         # 下载数据中心页数据, 有的账户没有
          creative_guidance: ['美食', '财经']     # 下载创作灵感页数据
          billboard: ['音乐', '财经']             # 下载抖音排行榜数据
      home:                                     # 配置: 抖音官网首页
        operate:
          comment: True                       # 配置: 自动回复评论, 回复内容由"default_comment_reply_message"或"ai_prompt_content_comment_reply"决定
          chat: True                          # 配置: 自动处理私聊, 评论内容由"default_chat_reply_message"或"ai_prompt_content_chat_reply"决定
        discover:                             # 浏览抖音首页视频, 通过"ai_prompt_content_filter"可以过滤视频内容
          topics: ['首页', '娱乐榜']            # 浏览的榜单, 输入"首页"则首页随机刷
          times: 3                            # 每个榜单点击几个视频
          actions: ['点赞', '收藏', '评论']     # 浏览时执行的动作, 评论内容由"default_comment_message"或"ai_prompt_content_comment"决定
          mention: ['52320237368', ]          # 如果需要评论, 评论时提及某人, 抖音号
        download:                             # 配置: 将指定户视频数据下载到本地
          ids: ['52320237368', ]              # 指定用户的抖音号
        comment:                              # 配置: 浏览指定用户视频
          ids: ['52320237368', ]              # 指定用户的抖音号
          times: 3                            # 每个用户浏览3个视频
          actions: ['点赞', '收藏', '评论']     # 浏览时执行的动作, 评论内容由"default_comment_message"或"ai_prompt_content_comment"决定
          mention: ['52320237368', ]          # 如果需要评论, 评论时提及某人, 抖音号
          shuffle: False                      # 随机选择浏览用户的视频, False则顺序浏览
        follow:                                             # 配置: 从指定用户的评论区私聊别人, 通过"ai_prompt_user_filter"可以判断是否为目标用户, 私聊信息"default_chat_message"
          ids: ['52320237368', ]                            # 用户的抖音号
          times: 3                                          # 每个用户选择3个视频
          batch: 3                                          # 每个视频评论区选择3个好友
          shuffle: False                                    # 随机选择用户的视频, False则顺序浏览
